{% set name = "tespy" %}
{% set version = "0.9.4.post2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tespy-{{ version }}.tar.gz
  sha256: 63de069fbd0679160e24ff8ecbbbc7d89cff3cb1e164d53bd4247c0b3ff94ecd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - pint
    - scipy
    - python >={{ python_min }}
    - coolprop >=6.8
    - jinja2
    - matplotlib-base >=3.2.1
    - numpy >=1.13.3
    - pandas >=1.3.0
    - tabulate >=0.8.2

test:
  imports:
    - tespy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://oemof.org/libraries/#tespy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Thermal Engineering Systems in Python (TESPy)
  description: |
    Thermal Engineering Systems in Python (TESPy). This package 
    provides a powerful simulation toolkit for thermal engineering plants
    such as power plants, district heating systems or heat pumps.
  doc_url: http://tespy.readthedocs.io/en/master/
  dev_url: https://github.com/oemof/tespy

extra:
  recipe-maintainers:
    - jan-janssen
