{% set name = "tespy" %}
{% set version = "0.7.6.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tespy-{{ version }}.tar.gz
  sha256: 0f1425ac6994410c4eec9782a245c0f390567ea6eef2411a25b872db6c61ef2a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.9
    - coolprop >=6.6
    - jinja2
    - matplotlib-base >=3.2.1
    - numpy >=1.13.3
    - pandas >=1.3.0
    - tabulate >=0.8.2

test:
  imports:
    - tespy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://oemof.org/libraries/#tespy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Thermal Engineering Systems in Python (TESPy)
  description: |
    Thermal Engineering Systems in Python (TESPy). This package 
    provides a powerful simulation toolkit for thermal engineering plants
    such as power plants, district heating systems or heat pumps.
  doc_url: http://tespy.readthedocs.io/en/master/
  dev_url: https://github.com/oemof/tespy

extra:
  recipe-maintainers:
    - jan-janssen
