{% set name = "tespy" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a4c2d0512caffcdbf004a2786c1611ee6d6dc90607057510a0884237973d0831

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
    - setuptools_scm
    - flit-core
  run:
    - coolprop >=6.4,<7
    - numpy >=1.13.3,<2
    - pandas >=0.19.2,!=1.0.0,<2
    - python >=3.9
    - scipy >=0.19.1,<2
    - tabulate >=0.8.2,<0.9

test:
  imports:
    - tespy
    - tespy.components
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://oemof.org/libraries/#tespy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Thermal Engineering Systems in Python (TESPy)
  description: |
    Thermal Engineering Systems in Python (TESPy). This package 
    provides a powerful simulation toolkit for thermal engineering plants
    such as power plants, district heating systems or heat pumps.
  doc_url: http://tespy.readthedocs.io/en/master/
  dev_url: https://github.com/oemof/tespy

extra:
  recipe-maintainers:
    - jan-janssen
