{% set name = "tespy" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tespy-{{ version }}.tar.gz
  sha256: 390e517a469d01f43eb8f2066105a429b82d50c72b78cd9b67e8eb173d61fd3d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.9
    - coolprop >=6.6,<7
    - jinja2
    - matplotlib-base >=3.2.1,<4
    - numpy >=1.13.3,<2
    - pandas >=1.3.0,<3
    - tabulate >=0.8.2,<0.9

test:
  imports:
    - tespy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://oemof.org/libraries/#tespy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Thermal Engineering Systems in Python (TESPy)
  description: |
    Thermal Engineering Systems in Python (TESPy). This package 
    provides a powerful simulation toolkit for thermal engineering plants
    such as power plants, district heating systems or heat pumps.
  doc_url: http://tespy.readthedocs.io/en/master/
  dev_url: https://github.com/oemof/tespy

extra:
  recipe-maintainers:
    - jan-janssen
