{% set name = "tespy" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/TESPy-{{ version }}.tar.gz
  sha256: e513f57693ca4cfbfa154d425c3ad37fe7d3a1abec5a865cc3abbbb12301895e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<3.9
  run:
    - coolprop >=6.4,<7
    - numpy >=1.13.3,<2
    - pandas >=0.19.2,!=1.0.0,<2
    - python >=3.6,<3.9
    - scipy >=0.19.1,<2
    - tabulate >=0.8.2,<0.9

test:
  imports:
    - tespy
    - tespy.components
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://oemof.org/libraries/#tespy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Thermal Engineering Systems in Python (TESPy)
  description: |
    Thermal Engineering Systems in Python (TESPy). This package 
    provides a powerful simulation toolkit for thermal engineering plants
    such as power plants, district heating systems or heat pumps.
  doc_url: http://tespy.readthedocs.io/en/master/
  dev_url: https://github.com/oemof/tespy

extra:
  recipe-maintainers:
    - jan-janssen
